{
 "title": "Westend to Millau Header Sync Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Difference Between Source and Target Headers",
   "type": "graph",
   "description": "Shows how many headers behind the target chain is from the source chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(Westend_to_Millau_Sync_best_source_block_number) - max(Westend_to_Millau_Sync_best_source_at_target_block_number)"
    }
   ]
  },
  {
   "title": "Headers Synced on Millau (Last 2 Mins)",
   "type": "graph",
   "description": "How many headers has the relay synced from the source node in the last 2 mins?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(Westend_to_Millau_Sync_best_source_block_number[10m])-min_over_time(Westend_to_Millau_Sync_best_source_block_number[10m])",
     "legendFormat": "Number of new Headers on Westend (Last 10 Mins)"
    }
   ]
  },
  {
   "title": "Best Blocks according to Relay",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_best_source_block_number",
     "legendFormat": "Best Known Westend Header at Westend"
    },
    {
     "expr": "Westend_to_Millau_Sync_best_source_at_target_block_number",
     "legendFormat": "Best Known Westend Header at Millau"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_average_load{instance='relay-headers-westend-to-millau:9616'}",
     "legendFormat": "Average system load in last {{over}}"
    }
   ]
  },
  {
   "title": "Relay Process CPU Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage_percentage{instance='relay-headers-westend-to-millau:9616'}[1m])",
     "legendFormat": "1 CPU = 100"
    }
   ]
  },
  {
   "title": "Whether with-Westend-grandpa-pallet and Westend itself are on different forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Westend_to_Millau_Sync_is_source_and_source_at_target_using_different_forks",
     "legendFormat": "On different forks?"
    }
   ]
  },
  {
   "title": "Memory Usage for Relay Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_memory_usage_bytes{instance='relay-headers-westend-to-millau:9616'} / 1024 / 1024",
     "legendFormat": "Process memory, MB"
    }
   ]
  }
 ]
}