{
 "title": "Rialto+Millau maintenance dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rialto: storage proof overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rialto_storage_proof_overhead{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Actual overhead"
    },
    { "expr": "1024", "legendFormat": "At runtime (hardcoded)" }
   ]
  },
  {
   "title": "Millau: Rialto -> Millau conversion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kusama_to_base_conversion_rate{instance='relay-millau-rialto:9616'} / polkadot_to_base_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Outside of runtime (actually Polkadot -> Kusama)"
    },
    {
     "expr": "Millau_Rialto_to_Millau_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "At runtime"
    }
   ]
  },
  {
   "title": "Millau: storage proof overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "millau_storage_proof_overhead{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Actual overhead"
    },
    { "expr": "1024", "legendFormat": "At runtime (hardcoded)" }
   ]
  },
  {
   "title": "Rialto: Millau -> Rialto conversion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_to_base_conversion_rate{instance='relay-millau-rialto:9616'} / kusama_to_base_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Outside of runtime (actually Kusama -> Polkadot)"
    },
    {
     "expr": "Rialto_Millau_to_Rialto_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "At runtime"
    }
   ]
  }
 ]
}