{
 "title": "Parachains Liveliness",
 "description": "Information related to the operation of parachains",
 "tags": [
  "Kusama",
  "Polkadot",
  "Parachains",
  "On-call"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Source of data", "query": "prometheus" },
   { "name": "chain", "label": "Chain", "query": "kusama,polkadot" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relay chain finality lag (avg)",
   "type": "gauge",
   "description": "Measures how far behind finality is compared to the current best block. By design, GRANDPA never finalizes past last 2 blocks, so this value is always >=2.",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(polkadot_block_height{chain=\"$chain\",instance=~\".*validator.*\", status=\"best\"} - on(    instance) polkadot_block_height{chain=\"$chain\",instance=~\".*validator.*\", status=\"finalized\"})"
    }
   ]
  },
  {
   "title": "Approval checking finality lag (avg)",
   "type": "gauge",
   "description": "The distance (in blocks) between the chain head and the last block \non which Approval voting is happening. The block is generally the highest approved ancestor of the head \nblock and the metric is computed during relay chain selection.",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\", instance=~\".*validator.*\"})"
    }
   ]
  },
  {
   "title": "Disputes Finality Lag (avg)",
   "type": "gauge",
   "description": "How far behind the chain head is the last approved and non disputed block. \nThis value is always higher than approval checking lag as it further restricts finality to only undisputed \nchains.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(polkadot_parachain_disputes_finality_lag{chain=\"$chain\"})"
    }
   ]
  },
  {
   "title": "Approval checking finality lag (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "polkadot_parachain_approval_checking_finality_lag{chain=\"$chain\", instance=~\".*validator.*\"}"
    }
   ]
  },
  {
   "title": "Disputes finality lag (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "polkadot_parachain_disputes_finality_lag{chain=\"$chain\", instance=~\".*validator.*\"}"
    }
   ]
  },
  {
   "title": "PVF preparation time (heatmap)",
   "type": "heatmap",
   "description": "The time spent in preparing Parachain Validation Function artifacts in seconds.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(polkadot_pvf_preparation_time_bucket{instance=~\".*validator.*\", chain=\"$chain\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PVF execution time (heatmap)",
   "type": "heatmap",
   "description": "Parachain Validation Function execution time distribution.  PVFs are expected to have a limited execution time to ensure there is enough time left for the parachain block to be included in the relay block. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_pvf_execution_time_bucket{instance=~\".*validator.*\", chain=\"$chain\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Candidate backing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Candidate backing",
   "type": "timeseries",
   "description": "Number of candidates seconded and signed statements.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_candidate_backing_candidates_seconded_total{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Candidates seconded"
    },
    {
     "expr": "sum(rate(polkadot_parachain_candidate_backing_signed_statements_total{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Statements signed"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Number of erasure-encoded chunks of data belonging to candidate blocks. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "chunks/s" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_received_availability_chunks_total{chain=\"$chain\", instance=~\".*validator.*\"}[$__rate_interval]))",
     "legendFormat": "Chunks received"
    }
   ]
  },
  { "title": "Disputes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Dispute votes and outcomes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "disputes/s" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_candidate_dispute_concluded{chain=\"$chain\"}[$__rate_interval])) by (validity)",
     "legendFormat": "Concluded {{validity}}"
    },
    {
     "expr": "sum(rate(polkadot_parachain_candidate_disputes_total{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "disputes raised"
    },
    {
     "expr": "sum(rate(polkadot_parachain_candidate_dispute_votes{chain=\"$chain\"}[$__rate_interval])) by (validity)",
     "legendFormat": "{{validity}} votes"
    }
   ]
  },
  {
   "title": "Dispute participations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "disputes/s" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_dispute_participations{chain=\"$chain\"}[$__rate_interval])) by (priority)",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  { "title": "Candidate Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Candidate Validation Times (distribution)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_candidate_validation_validate_from_chain_state_bucket{chain=\"$chain\"} [$__rate_interval])) by (le) +\nsum(increase(polkadot_parachain_candidate_validation_validate_from_exhaustive_bucket{chain=\"$chain\"} [$__rate_interval])) by (le) +\nsum(increase(polkadot_parachain_candidate_validation_validate_candidate_exhaustive_bucket{chain=\"$chain\"} [$__rate_interval])) by (le)\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Candidates imported/seconded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_imported_candidates_total{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Imported"
    },
    {
     "expr": "sum(increase(polkadot_parachain_candidate_backing_candidates_seconded_total{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Seconded"
    }
   ]
  },
  {
   "title": "Candidate validation requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_validation_requests_total{chain=\"$chain\"}[$__rate_interval])) by (validity)",
     "legendFormat": "{{validity}}"
    }
   ]
  },
  { "title": "Approval voting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Assignment Delay Tranches",
   "type": "heatmap",
   "description": "Approval voting requires that validators which are assigned to check a specific \ncandidate are split up into delay tranches (0.5s each). Then, all validators checks are ordered by the delay \ntranche index. Early tranches of validators will check the candidate first and later tranches act as as backups in case of no shows.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(polkadot_parachain_assignments_produced_bucket{chain=\"$chain\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Assignments, approvals and no shows",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_assignments_produced_count{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Assignments"
    },
    {
     "expr": "sum(rate(polkadot_parachain_approvals_produced_total{chain=\"$chain\"}[$__rate_interval])) by (status)",
     "legendFormat": "Approvals ({{status}})"
    },
    {
     "expr": "sum(rate(polkadot_parachain_approvals_no_shows_total{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "No shows"
    }
   ]
  },
  {
   "title": "Time to Recover and Check Candidate",
   "type": "timeseries",
   "description": "This covers the full time it takes to: recover candidate available data from other validators; check the candidate; issue statement or initiate dispute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(polkadot_parachain_time_recover_and_approve_bucket{chain=\"$chain\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th %"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(polkadot_parachain_time_recover_and_approve_bucket{chain=\"$chain\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th %"
    }
   ]
  },
  {
   "title": "Assignments and approvals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(polkadot_parachain_assignments_produced_count{chain=\"$chain\"}[$__rate_interval]))",
     "legendFormat": "Assignments"
    },
    {
     "expr": "sum(rate(polkadot_parachain_approvals_produced_total{chain=\"$chain\"}[$__rate_interval])) by (status)",
     "legendFormat": "Approvals ({{status}})"
    }
   ]
  }
 ]
}