{
 "title": "Beefy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Beefy Best block",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_beefy_best_block{chain=\"rialto_local\"}",
     "legendFormat": "Rialto(Charlie)"
    },
    {
     "expr": "substrate_beefy_best_block{chain=\"millau_local\"}",
     "legendFormat": "Millau(Charlie)"
    }
   ]
  },
  {
   "title": "Beefy Voting Rounds",
   "type": "stat",
   "gridPos": { "h": 14, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "substrate_beefy_should_vote_on{chain=\"rialto_local\"}",
     "legendFormat": "Rialto(Charlie) Should-Vote-On"
    },
    {
     "expr": "substrate_beefy_round_concluded{chain=\"rialto_local\"}",
     "legendFormat": "Rialto(Charlie) Round-Concluded"
    },
    {
     "expr": "substrate_beefy_should_vote_on{chain=\"millau_local\"}",
     "legendFormat": "Millau(Charlie) Should-Vote-On"
    },
    {
     "expr": "substrate_beefy_round_concluded{chain=\"millau_local\"}",
     "legendFormat": "Millau(Charlie) Round-Concluded"
    }
   ]
  },
  {
   "title": "Beefy Votes Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_beefy_votes_sent{chain=\"rialto_local\"}",
     "legendFormat": "Rialto (node Charlie)"
    },
    {
     "expr": "substrate_beefy_votes_sent{chain=\"millau_local\"}",
     "legendFormat": "Millau (node Charlie)"
    }
   ]
  },
  {
   "title": "Beefy Skipped Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_beefy_skipped_sessions{chain=\"rialto_local\"}",
     "legendFormat": "Rialto(Charlie)"
    },
    {
     "expr": "substrate_beefy_skipped_sessions{chain=\"millau_local\"}",
     "legendFormat": "Millau(Charlie)"
    }
   ]
  }
 ]
}